language: node_js
node_js:
  - "node"

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GH_TOKEN
  local_dir: build 
  on:
    branch: master
